version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27016:27017
  backend:
    image: node
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./:/opt/employee
    command: >
      bash -c "cd /opt/employee && npm i && cd frontend && npm i && npm run build && cd .. && cd backend && npm i && npm run start"
  web:
    image: nginx
    depends_on:
      - backend
    volumes:
      - ./dist:/opt/employee/src/dist
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8081:80
    environment:
      - NGINX_HOST=employee.loc
      - NGINX_PORT=80
